version: 2
dist: ./dist

builds:
  - binary: fusion
    main: ./cmd/server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm
        goarm: 6
      - goos: windows
        goarch: arm
        goarm: 7

archives:
  - id: default
    formats: ["binary"]
    # Additional files/globs you want to add to the archive.
    files:
      - "LICENSE*"
      - "README*"

checksum:
  algorithm: sha256
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

release:
  draft: true

changelog:
  use: github-native
